paths:
  /sessions/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/confirm-register/{token}:
    get:
      summary: Confirm user registration
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: The confirmation token
      responses:
        '200':
          description: User confirmed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/restore:
    post:
      summary: Initiate password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordReset'
      responses:
        '200':
          description: Password reset initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/reset/{hash}:
    get:
      summary: Validate password reset link
      parameters:
        - in: path
          name: hash
          required: true
          schema:
            type: string
          description: The password reset hash
      responses:
        '200':
          description: Password reset link validated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/new-password/{hash}:
    post:
      summary: Set a new password
      parameters:
        - in: path
          name: hash
          required: true
          schema:
            type: string
          description: The password reset hash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPassword'
      responses:
        '200':
          description: New password set successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/logout:
    get:
      summary: Logout user
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /sessions/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/current:
    get:
      summary: Get current user
      responses:
        '200':
          description: Current user retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/github:
    get:
      summary: Initiate GitHub authentication
      responses:
        '302':
          description: Redirect to GitHub authentication

  /sessions/githubCallback:
    get:
      summary: Handle GitHub authentication callback
      responses:
        '302':
          description: Redirect to GitHub authentication success

components:
  schemas:
    RegisterUser:
      type: object
      required:
        - first_name
        - last_name
        - email
        - age
        - password
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        age:
          type: integer
        password:
          type: string

    User:
      $ref: '../model/users.model.js#/components/schemas/User'

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    SuccessResponse:
      type: object
      properties:
        message:
          type: string

    PasswordReset:
      type: object
      required:
        - email
      properties:
        email:
          type: string

    NewPassword:
      type: object
      required:
        - password
      properties:
        password:
          type: string

    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string