swagger: '2.0'
info:
  description: "API for managing carts in FakeLibre, an eCommerce platform for the Coderhouse backend course."
  version: "1.0.0"
  title: "FakeLibre Cart API"
paths:
  /carts/{cid}:
    get:
      summary: "Get a cart by cart ID."
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Cart found"
        404:
          description: "Cart not found"
        500:
          description: "Internal server error"
  /carts/user/{id}:
    get:
      summary: "Get a cart by user ID."
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Cart found"
        404:
          description: "Cart not found"
        500:
          description: "Internal server error"
  /carts:
    post:
      summary: "Create a new cart."
      responses:
        201:
          description: "Cart created"
        500:
          description: "Internal server error"
  /carts/{cid}/products/{pid}/{quantity}:
    post:
      summary: "Add a product to the cart."
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
        - in: path
          name: quantity
          required: true
          schema:
            type: number
      responses:
        201:
          description: "Product added to cart"
        403:
          description: "You cannot add your own products to the cart"
        404:
          description: "Cart or product not found"
        500:
          description: "Internal server error"
  /carts/{cid}/products/{pid}:
    delete:
      summary: "Delete a product from the cart by its ID."
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Product deleted from cart"
        404:
          description: "Cart or product not found"
        500:
          description: "Internal server error"
  /carts/{cid}/purchase:
    post:
      summary: "Purchase the cart."
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Cart purchased successfully"
        400:
          description: "Some products could not be purchased due to insufficient stock"
        500:
          description: "Internal server error"
  /cart:
    post:
      summary: "Create or retrieve the user's cart."
      responses:
        200:
          description: "Cart obtained or created successfully"
        500:
          description: "Internal server error"